### ISSUE TITLE
In PDF, straight quotes are getting turned into back quotes in a parsed literal in the About section

### ISSUE THREAD

**Issue by DavidGriffith** [i6/ibg#11]
We see `print "*string*";` which is supposed to render as straight quotes surrounding italics.  Instead I'm getting back quotes at the beginning when rendering to PDF.  The quotes at the end are okay.  According to http://www.sphinx-doc.org/en/stable/changes.html, this was fixed in Sphinx 1.2.3. Maybe a new bug needs to be filed?

**Comment by zondo** [comment]
Fixed this using the Sphinx 'samp' directive instead of parsed-literal.
