### ISSUE TITLE
Text included by way of literalinclude directives is too wide for the border in html mode

### ISSUE THREAD

**Issue by DavidGriffith** [i6/ibg#12]
At least in the appendices when transcripts and game source are presented by way of literalinclude directives, the resulting box around the text is too narrow.  Even though the transcripts and sources are all at 80 columns of width, some chunks of text are cut off at the right side when the document is compiled to HTML.

**Comment by zondo** [comment]
This can probably be fixed by increasing the `page_width` value of `html_theme_options` in `conf.py`.

**Comment by DavidGriffith** [comment]
Fixed in c6f14da829dc141294413c37f3c6b7de21244dcb
