### ISSUE TITLE
Built-in Inform6 syntax highlighting is a bit dodgy

### ISSUE THREAD

**Issue by DavidGriffith** [i6/ibg#13]
The Inform6 syntax highlighting built into Sphinx is a bit dodgy.  It reports problems lexing chunks of code like this:

  ibg/chapters/10.rst:179: WARNING: Could not lex literal_block as "inform6". Highlighting skipped.

We might have to pull in Sphinx's code to tools/ and tweak it as we see fit.

**Comment by zondo** [comment]
It's actually [Pygments](http://pygments.org/) that does the highlighting, but yes, if it's not doing the Right Thing we can make a local fixed version (and hand it back to the Pygments people at some point).

**Comment by DavidGriffith** [comment]
I've pulled in the relevant file from Pygments into the tools/ directory and switched the system to using that.

**Comment by zondo** [comment]
I notice that in many of the places where the lexer complains, its complaint is valid.  The places where `...` is inserted, to represent a bunch of random code, are not valid inform6 syntax.  It might be better to replace these with a comment that is (e.g., `! ...` or `! <inform code>`).

**Comment by zondo** [comment]
A simpler solution to this might be to resurrect my original highlighter, which is much more forgiving about things.  The Pygments version seems to be expecting more complete code than a lot of the snippets in this guide, and it could be quite a big job convincing it otherwise.

**Comment by zondo** [comment]
Fixed by a94081289bc21041a8daac44d8c8b6714a831281.
