### ISSUE TITLE
Use vector graphics for object tree diagrams

### ISSUE THREAD

**Issue by catdisc** [i6/ibg#6]
I wonder if the images should be vector graphics? This seems like a less opaque format, as the file can be directly edited, and more like a "source" file, especially since most of them seem (well, at least the Heidi files) are just boxes with some text and connecting lines. Plus, I understand the that there was a desire to publish a printed book? Vector graphics would probably look nicer.

**Comment by zondo** [comment]
Yes, the object tree diagrams are ideal for making into vector graphics.  I've been looking at [Blockdiag](https://pypi.python.org/pypi/blockdiag); there's a nice Sphinx extension which lets you embed the diagrams into docs directly.  I'll add this to the TODO list.

**Comment by zondo** [comment]
Implemented by d243892ad9717d0d1cbb0dbc941b229b24a7f09e.
