### ISSUE TITLE
Table of contents and chapter numbering is wrong when building latexpdf output.

### ISSUE THREAD

**Issue by DavidGriffith** [i6/ibg#7]
The "Copyright", "Release history", "Foreword by Graham Nelson", and "About this guide" foreword sections are supposed to be unnumbered.  This happens when using the "html" build target, but not when using the "latexpdf" target.

**Comment by DavidGriffith** [comment]
Along with this, we need to figure out how to include content before the table of contents is printed.

**Comment by zondo** [comment]
Fixed by 39cd6425a62326e42786da4597378a0c97111214.
